blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/turbine-queue/turbine/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
  - name: Documentation
    url: https://github.com/turbine-queue/turbine#readme
    about: Check the documentation before opening an issue
